---
title: "Analyze networks"
format: 
  html:
    toc: true
    toc-depth: 3
editor: source
author: 
  - name: "Lisa Nicvert"
    orcid: 0009-0006-5763-0865
  - name: "Hervé Fritz"
    orcid: 0000-0002-7106-3661
  - name: "Stéphane Dray"
    orcid: 0000-0003-0153-1105
embed-resources: true
params:
  thr: 1
  colco: "darkred"
  colli: "cornflowerblue"
  log_transform_traits: TRUE
  transform_matrix: ""
bibliography: references.bib
---


```{r}
#| code-fold: true
#| output: false

library(here)

library(ggplot2)
library(patchwork)

library(ade4)
library(adegraphics)

library(effectsize)

devtools::load_all()

set.seed(42)
```

```{r}
# Number of permutations for variance partitioning
nrepet <- 999

# Paths
out_folder <- here("outputs", "04_all_networks")

figures_folder <- here("figures")
input_folder <- file.path(here("outputs/01_clean_data"))
```

## Read data

```{r read_data}
# Iterate folders to get data
dirs <- list.dirs(input_folder, full.names = FALSE)
dirs <- dirs[dirs != ""]

# Initialize lists
inter_list <- list()
pt_list <- list()
bt_list <- list()
for (dir in dirs) {
  inter <- read.csv(file.path(input_folder, dir, 
                              "interactions.csv"))
  pt <- read.csv(file.path(input_folder, dir, 
                              "plant_traits.csv"))
  bt <- read.csv(file.path(input_folder, dir, 
                              "bird_traits.csv"))
  
  # Store variables
  inter_list[[dir]] <- inter
  pt_list[[dir]] <- pt
  bt_list[[dir]] <- bt
}
```

```{r}
# Filter data (threshold and NA traits)

# Initialize species names list
pnames_list <- list()
bnames_list <- list()
for (i in 1:length(inter_list)) {
  # Filter matrix
  intermat <- df_to_matrix(inter_list[[i]], 
                           rows = "plant_species_code",
                           columns = "bird_species_code")
  intermat <- filter_matrix(intermat, thr = params$thr)
  
  if (params$log_transform_traits) {
    # Remove species with trait values equal to zero before filtering
    pt_list[[i]] <- pt_list[[i]] |> 
      filter(plant_species != "Miconia_307")
  }
  
  # Prepare traits
  pnames <- pt_list[[i]] |> 
    dplyr::select(plant_species_code, plant_species)
  pt_filtered <- pt_list[[i]] |>
    tibble::column_to_rownames("plant_species_code") |> 
    tidyr::drop_na() |> 
    dplyr::select(-plant_species) 
  
  bnames <- bt_list[[i]] |> 
    dplyr::select(bird_species_code, bird_species)
  bt_filtered <- bt_list[[i]] |>
    tibble::column_to_rownames("bird_species_code") |> 
    tidyr::drop_na() |> 
    dplyr::select(-bird_species) 
  
  # Filter
  p <- intersect(rownames(intermat), rownames(pt_filtered))
  b <- intersect(colnames(intermat), rownames(bt_filtered))
  
  pt_filtered <- pt_filtered[p, ]
  bt_filtered <- bt_filtered[b, ]
  intermat <- intermat[p, b]
  
  # Remove empty rows/columns
  keep_rows <- which(rowSums(intermat) != 0)
  keep_cols <- which(colSums(intermat) != 0)
  
  intermat <- intermat[keep_rows, keep_cols]
  pt_filtered <- pt_filtered[keep_rows, ]
  bt_filtered <- bt_filtered[keep_cols, ]
  
  # Apply transformations (if needed)
  if (params$transform_matrix == "log1p") {
    # Transform matrix counts using log(x + 1)
    intermat <- log(intermat + 1)
  } else if (params$transform_matrix == "N2") {
    intermat <- douconca::ipf2N2(intermat)
  }
  
  if (params$log_transform_traits) {
    # Check there will not be Nas
    zero_pt <- which(pt_filtered <= 0, arr.ind = TRUE)
    if (nrow(zero_pt) != 0) {
      stop("Cannot log-transform plant trait less than zero")
    }
    
    zero_bt <- which(bt_filtered <= 0, arr.ind = TRUE)
    if (nrow(zero_bt) != 0) {
      stop("Cannot log-transform bird trait less than zero")
    }
    
    # Log-transform traits
    bt_filtered <- bt_filtered |> 
      dplyr::mutate(across(c(KippsIndex, BillLength, BillWidth, Bodymass), 
                           log))
    pt_filtered <- pt_filtered |> 
      dplyr::mutate(across(c(meanL, meanD1, meanHeight, CropMass), 
                           log))
  }

  # Store species code/names correspondences (not used)
  dataname <- names(inter_list)[i]
  pnames_list[[dataname]] <- pnames
  bnames_list[[dataname]] <- bnames
  
  # Update lists
  inter_list[[i]] <- data.frame(intermat)
  pt_list[[i]] <- pt_filtered
  bt_list[[i]] <- bt_filtered
}
```

## Variation partitioning

Loop datasets to partition variation:

```{r}
Rcor_df <- data.frame()

for (i in 1:length(inter_list)) {
  # Get corresponding interactions and traits
  inter <- inter_list[[i]]
  pt <- pt_list[[i]]
  bt <- bt_list[[i]]
  
  # Get dimensions
  r <- nrow(inter)
  c <- ncol(inter)
  l <- ncol(pt)
  k <- ncol(bt)
  
  # CA
  ca <- dudi.coa(inter, scannf = FALSE,
                 min(c(r - 1, c - 1)))
  
  # Variation partitioning
  vp <- dvaripart(Y = ca, 
                  dfR = pt, dfQ = bt)
  
  # Store R2 values and p-values
  R2_corr <- vp$R2.adj
  R2_raw <- vp$R2
  pval <- vp$test$pvalue
  
  # Format results
  Rcor <- data.frame(dataset = rep(names(inter_list)[i], 4), 
                     type = c("residual", 
                              "bird_traits", "plant_traits",
                              "matching"),
                     R2_corr = c(R2_corr["d"], 
                                 R2_corr["c"], R2_corr["a"], 
                                 R2_corr["b"]),
                     R2_raw = c(R2_raw["d"], 
                                R2_raw["c"], R2_raw["a"], 
                                R2_raw["b"]),
                     p = c(NA, pval[2], pval[1],
                           max(pval[c(3, 4)])))
  
  Rcor_df <- rbind(Rcor_df, Rcor)
}
```

## Results analysis

First, check that the $R^2$ sum to one.

```{r}
Rcor_df |> 
  dplyr::group_by(dataset) |> 
  dplyr::summarize(sum = sum(R2_corr)) |> 
  DT::datatable()
```


```{r}
# Filter out datasets with NAs (if any)
is_na <- unique(Rcor_df$dataset[is.na(Rcor_df$R2_corr)])
Rcor_df <- Rcor_df |>
  filter(!dataset %in% is_na)
```

```{r}
# Show negative R2
neg <- Rcor_df |> 
  dplyr::group_by(dataset) |> 
  dplyr::summarize(has_neg = any(R2_corr < 0)) |> 
  dplyr::filter(has_neg)

paste(nrow(neg), "datasets have negative R2 values:", 
      paste(neg$dataset, collapse = ", "), collapse = " ")

# Filter out negative R2
# Rcor_df <- Rcor_df |> dplyr::filter(!(dataset %in% neg$dataset))
```


```{r}
# Prepare df
Rcor_df <- Rcor_df |> dplyr::mutate(signif = p > 0.05)

# Format for labels
type_name_vector <- c("Residual [d]", "Bird traits [c]", "Plant traits [a]", "Matching [b]")
names(type_name_vector) <- c("residual", "bird_traits", "plant_traits", "matching")

Rcor_df <- Rcor_df |> 
  dplyr::mutate(type_name = type_name_vector[type], 
                .after = type) |> 
  dplyr::mutate(dataset_name = gsub("_", " ", dataset), 
                .after = dataset)

# Reorder factors
Rcor_df$type <- factor(Rcor_df$type, 
                       levels = names(type_name_vector))
Rcor_df$type_name <- factor(Rcor_df$type_name, 
                            levels = unname(type_name_vector))
```

### By dataset

```{r}
#| code-fold: true

Rcor_df |> 
  dplyr::arrange(dataset_name, type_name) |> 
  dplyr::select(-c(dataset, type)) |> 
  DT::datatable() |> 
  DT::formatRound(columns = c("R2_corr", "R2_raw", "p"), 
                  digits = 3)
```

### By source of variation

```{r}
#| code-fold: true

Rcor_df |> 
  dplyr::group_by(type_name) |> 
  dplyr::summarize(mean_R2 = mean(R2_corr),
                   median_R2 = median(R2_corr),
                   sd_R2 = sd(R2_corr),
                   prop_signif = sum(signif)/length(unique(dataset))) |> 
  DT::datatable() |> 
  DT::formatRound(columns = c("mean_R2", "median_R2", "sd_R2"), 
                  digits = 3)
```

### Plot

```{r}
#| code-fold: true

# Prepare data for plotting bars by dataset
coltype <- viridisLite::viridis(n = length(levels(Rcor_df$type_name)), 
                                begin = 0.1, end = 0.9)
names(coltype) <- levels(Rcor_df$type_name)

# Dataset order
subset <- Rcor_df[Rcor_df$type_name == "Residual [d]", ]
ord <- order(subset$R2_corr[subset$type_name =="Residual [d]"])
dataset_order <- subset$dataset_name[rev(ord)]

Rcor_df_bar <- Rcor_df
Rcor_df_bar$dataset_name <- factor(Rcor_df_bar$dataset_name, 
                                   levels = dataset_order, 
                                   ordered = TRUE)
```


```{r}
#| code-fold: true
#| output: false

# Plot by dataset
(gbar <- ggplot(Rcor_df_bar,
                aes(y = dataset_name, x = R2_corr, 
                    fill = type_name)) +
  geom_col() +
  geom_vline(xintercept = c(0, 1), linetype = "dashed") +
  scale_fill_manual(values = coltype, name = "Origin of variation") +
  guides(fill = guide_legend(reverse = TRUE)) +
  ylab("Dataset") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.key.spacing.x = unit(0.5, "cm"))
 )
```


```{r}
#| code-fold: true
#| output: false

# Plot by source of variation

# Precompute median for mabels
median <- tapply(Rcor_df$R2_corr, Rcor_df$type_name, median)
median_df <- data.frame(type_name = names(median),
                        median = median)

(gbox <- ggplot(Rcor_df,
               aes(y = forcats::fct_rev(type_name), 
                   x = R2_corr, color = type_name)) +
    geom_boxplot(show.legend = FALSE, 
                 width = 0.8,
                 outliers = FALSE) +
    geom_jitter(width = 0, height = 0.2,
                size = 0.8,
                show.legend = FALSE,
                aes(alpha = signif)) +
    scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.2)) +
    geom_label(data = median_df,
               aes(x = median, 
                   label = round(median, 3)),
               position = position_nudge(y = 0.4),
               # vjust = 0,
               size = 2.5,
               show.legend = FALSE) +
    scale_color_manual(values = coltype) +
    ylab("Origin of variation") +
    theme_minimal())
```

```{r}
#| fig-width: 9
#| fig-height: 5
#| code-fold: true

(gbar + plot_spacer() + gbox) + 
  # plot_annotation(title = "No filtering") +
  plot_layout(guides = 'collect',
              axis_titles = "collect", 
              widths = c(10, 0.5, 10)) &
  theme(legend.position='bottom') &
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),
                     limits = c(-0.2, 1.2),
                     expand = c(0, 0)) &
  xlab(bquote("Corrected"~R^2)) 

if (!params$log_transform_traits & params$transform_matrix == "") {
  ggsave(file.path(figures_folder, "Fig_4_dcca_var_networks.png"),
       width = 18, height = 10, units = "cm")
} else if (params$log_transform_traits){
  ggsave(file.path(figures_folder, "Fig_S1_S7_dcca_var_networks_log.png"),
       width = 18, height = 10, units = "cm")
} else if (params$transform_matrix == "N2"){
    ggsave(file.path(figures_folder, "Fig_S1_S9_dcca_var_networks_N2.png"),
       width = 18, height = 10, units = "cm")
}
```

```{r}
# Check if resudual R2 dimension decreases with dimension
dims <- lapply(inter_list, dim)
dims_prod <- sapply(dims, prod)
dims_df <- data.frame(dataset = names(dims_prod), 
                      dim = unname(dims_prod))

matching_cor <- Rcor_df |> dplyr::filter(type == "residual")

res <- matching_cor |> 
  dplyr::left_join(dims_df, by = "dataset")

ggplot(res, aes(x = dim, y = R2_corr)) +
  geom_smooth() +
  geom_point() +
  ylab("Residual correlation") +
  xlab("Product of dimensions") +
  theme_bw()
```

## Non-random variation (Appendix S1: Section S7)

```{r}
# Get p-values from chi-square test
chisq <- lapply(inter_list, 
                function(inter) {
                  chisq.test(inter, simulate.p.value = TRUE)
                })
pval <- sapply(chisq, function(c) c$p.value)
pval_adj <- p.adjust(pval, method = "holm")
pval_adj <- signif(pval_adj, 3)

# Get statistic
stat <- sapply(chisq, function(c) signif(c$statistic, 3))

# Get Cramer effect sizes
V_effect <- lapply(inter_list, 
                   function(inter) {
                     signif(effectsize::cramers_v(inter), 3)
                     })

V <- sapply(V_effect, 
            function(Vi) Vi$Cramers_v_adjusted)

V_CI <- sapply(V_effect, 
               function(Vi) {
                 paste0("[", 
                        signif(Vi$CI_low, 3), "-", 
                        signif(Vi$CI_high, 3), "]")
                 })

# Get effect size interpretation
effect_scale <- c("small" = 0.1, "medium" = 0.3, "large" = 0.5)
small_index <- which(V < effect_scale["small"])
medium_index <- which(V >= effect_scale["medium"] & 
                        V < effect_scale["large"])
large_index <- which(V >= effect_scale["large"])
effect_size <- rep(NA, length(V))
effect_size[small_index] <- "small"
effect_size[medium_index] <- "medium"
effect_size[large_index] <- "large"

# Create and display table
df_non_random <- data.frame(dataset = names(inter_list),
                            chisq = stat,
                            p_value = pval_adj,
                            V = V,
                            V_CI = V_CI,
                            effect_size = effect_size)
rownames(df_non_random) <- NULL
DT::datatable(df_non_random)
```


```{r}
if (!params$log_transform_traits & params$transform_matrix == "") {
  # Export table for LateX
  df_non_random$dataset <- gsub("_", "\\\\_", df_non_random$dataset)
  write.table(df_non_random, sep = " & ", 
              eol = " \\\\\n\\hline\n",
              quote = FALSE, 
              col.names = FALSE, row.names = FALSE, 
              file = file.path(out_folder, "non-random.txt"))
}

```
